/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard/': typeof DashboardIndexRoute
  '/overview/': typeof OverviewIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardIndexRoute
  '/overview': typeof OverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard/': typeof DashboardIndexRoute
  '/overview/': typeof OverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard/' | '/overview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/overview'
  id: '__root__' | '/dashboard/' | '/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
